name: HealthBar
main: org.necavi.minecraft.healthbar.HealthBar
version: 1.0
author: Plornt & Necavi
description: Adds a healthbar for SpoutClients.
depend: [Spout]
softdepend: [Heroes]
commands:
  healthbar:
    description: Provides functions to reload the config.
    usage: healthbar

permissions:
  healthbar:
    description: HealthBar permissions
    type: map
    map:
      cansee:
        description: Whether a player can see the health bar.
        type: boolean
        default: false
      reload:
        description: Whether or not a player may reload the configuration
        type: boolean
        default: false